apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup-manager.fullname" . }}-config
data:
  SRC_PATH: "{{ .Values.configMap.data.SRC_PATH }}"
  BACKUP_PATH: "{{ .Values.configMap.data.BACKUP_PATH }}"
  WEB_UI: "{{ .Values.configMap.data.WEB_UI }}"
  WEBHOOK_URL: "{{ .Values.configMap.data.WEBHOOK_URL }}"