apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  labels:
    {{- include "immich-machine-learning.labels" . | nindent 4 }}
spec:
  type: {{ .Values.immichMachineLearning.service.type }}
  ports:
    - port: {{ .Values.immichMachineLearning.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "immich-machine-learning.selectorLabels" . | nindent 4 }}
