apiVersion: v1
kind: Secret
metadata:
  name: immich-server-secrets
  namespace: immich
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD }}
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME }}