apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whisper.fullname" . }}-config
data:
  ASR_MODEL: "{{ .Values.configMap.data.ASR_MODEL }}"
  ASR_ENGINE: "{{ .Values.configMap.data.ASR_ENGINE }}"