apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}-config
data:
  API_KEY: "{{ .Values.configMap.data.API_KEY }}"
  ZONE: "{{ .Values.configMap.data.ZONE }}"
  SUBDOMAIN: "{{ .Values.configMap.data.SUBDOMAIN }}"