apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  labels:
    {{- include "immich-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.immichRedis.service.type }}
  ports:
    - port: {{ .Values.immichRedis.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "immich-redis.selectorLabels" . | nindent 4 }}
