apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    {{- include "immich-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.immichServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "immich-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.immichServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "immich-server.labels" . | nindent 8 }}
        {{- with .Values.immichServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.immichServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.global.serviceAccount.name | quote }}
      securityContext:
        {{- toYaml .Values.immichServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: immich-server-config
                  key: DB_DATABASE_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: immich-server-config
                  key: DB_PORT
            - name: REDIS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-server-config
                  key: REDIS_HOSTNAME
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-server-config
                  key: DB_HOSTNAME
            - name: IMMICH_MACHINE_LEARNING_URL
              valueFrom:
                configMapKeyRef:
                  name: immich-server-config
                  key: IMMICH_MACHINE_LEARNING_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-server-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-server-secrets
                  key: DB_PASSWORD
          securityContext:
            {{- toYaml .Values.immichServer.securityContext | nindent 12 }}
          image: "{{ .Values.immichServer.image.repository }}:{{ .Values.immichServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.immichServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.immichServer.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.immichServer.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.immichServer.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.immichServer.resources | nindent 12 }}
          {{- with .Values.immichServer.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.immichServer.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.immichServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.immichServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.immichServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
