apiVersion: v2
name: jackett
description: API Support for your favorite torrent trackers.
type: application
version: 1.0.0
appVersion: "latest"
icon: https://lignux.com/wp-content/uploads/2021/06/Jackett-logo.png