kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "immich-pv"