apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secrets
  namespace: immich
type: Opaque
data:
  POSTGRES_USER: {{ .Values.immichDb.secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.immichDb.secrets.POSTGRES_PASSWORD }}