apiVersion: v1
kind: Service
metadata:
  name: immich-db
  labels:
    {{- include "immich-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.immichDb.service.type }}
  ports:
    - port: {{ .Values.immichDb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "immich-db.selectorLabels" . | nindent 4 }}
