apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bazarr.fullname" . }}-config
data:
  PUID: "{{ .Values.configMap.data.PUID }}"
  PGID: "{{ .Values.configMap.data.PGID }}"
  TZ: "{{ .Values.configMap.data.TZ }}"