{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "node-red.fullname" . }}-pvc
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}
  volumeName: "node-red-pv"