apiVersion: v2
name: cloudflared
description: Cloudflared is a simple Docker image for running Cloudflared.
type: application
version: 1.0.0
appVersion: "latest"
icon: https://static-00.iconduck.com/assets.00/cloudflare-icon-2048x926-mxn8koxq.png