apiVersion: v2
name: vaultwarden
description: Vaultwarde is an unofficial Bitwarden compatible server written in Rust.
type: application
version: 1.0.0
appVersion: "latest"
icon: https://static-00.iconduck.com/assets.00/bitwarden-icon-2048x2048-dpfdlf2a.png