apiVersion: v2
name: prowlarr
description: Prowlarr is a newsgroup indexer manager.
type: application
version: 1.0.0
appVersion: "latest"
icon: https://static-00.iconduck.com/assets.00/prowlarr-icon-1024x1024-vyf0hy1t.png